apiVersion: v1
kind: Service
metadata:
  labels:
    app: iot
  name: iot
spec:
  ports:
    - name: iot
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: iot
  type: LoadBalancer