apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: iot
  name: iot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: iot
    spec:
      containers:
        - name: iot
          image: rndcontainer.azurecr.io/wearables-nodejs:87
          ports:
          - containerPort: 3000
            protocol: TCP
      imagePullSecrets:
      - name: rndregistry